FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    hping3 \
    iputils-ping \
    dnsutils \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

CMD ["bash"]
