FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y hping3 iputils-ping curl && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /scripts

CMD ["bash"]
